package com.example.android.sunshine;

public final class WeatherData {

    public static String[] getWeather() {
        return new String[]{
                "JAN BLAH Monday",
                "JAN BLAH Tuesday",
                "JAN BLAH Wednesday",
                "JAN BLAH Thursday",
                "JAN BLAH Friday",
                "JAN BLAH Saturday",
                "JAN BLAH Sunday",
                "JAN BLAH Monday",
                "JAN BLAH Tuesday",
                "JAN BLAH Wednesday",
                "JAN BLAH Thursday",
                "JAN BLAH Friday",
                "JAN BLAH Saturday",
                "JAN BLAH Sunday",
                "JAN BLAH Monday",
                "JAN BLAH Tuesday",
                "JAN BLAH Wednesday",
                "JAN BLAH Thursday",
                "JAN BLAH Friday",
                "JAN BLAH Saturday",
                "JAN BLAH Sunday",
                "JAN BLAH Monday",
                "JAN BLAH Tuesday",
                "JAN BLAH Wednesday",
                "JAN BLAH Thursday",
                "JAN BLAH Friday",
                "JAN BLAH Saturday",
                "JAN BLAH Sunday",
                "JAN BLAH Monday",
                "JAN BLAH Tuesday",
                "JAN BLAH Wednesday",
                "JAN BLAH Thursday",
                "JAN BLAH Friday",
                "JAN BLAH Saturday",
                "JAN BLAH Sunday",
                "JAN BLAH Monday",
                "JAN BLAH Tuesday",
                "JAN BLAH Wednesday",
                "JAN BLAH Thursday",
                "JAN BLAH Friday",
                "JAN BLAH Saturday",
                "JAN BLAH Sunday",
                "JAN BLAH Monday",
                "JAN BLAH Tuesday",
                "JAN BLAH Wednesday",
                "JAN BLAH Thursday",
                "JAN BLAH Friday",
                "JAN BLAH Saturday",
                "JAN BLAH Sunday",
        };
    }
}